"""
Mock pipeline seeder.

Seeds the pipeline with real Q&A pairs from the HuggingFace benchmark training set
(dipenbhuva/home-diy-repair-qa) so the full phases 1–6 + Phase A agreement can run
without any LLM API credentials.

Phases 4 and 5 use per-dimension Bernoulli draws instead of judge calls; human labels
are generated by perturbing quality eval scores with configurable agreement noise.

Usage:
  python main.py mock
  python main.py mock --batch-label baseline-mock --num-samples 50 --seed 42
  python main.py mock --skip-human-labels
"""

import json
from datetime import datetime, timezone
from pathlib import Path

import numpy
import pandas as pd

from schema import (
    FAILURE_MODE_FIELDS,
    HUMAN_TO_LLM,
    QUALITY_DIMENSION_FIELDS,
    FailureLabelResult,
    QualityEvalResult,
    ValidatedResult,
)

MOCK_DEFAULTS: dict = {
    # Per-dim rates are tuned so the *combined* metrics match real baselines:
    #   overall_failure = any(6 dims) → ~21%  (real runs: 11–28%)
    #   overall_quality_pass = all(9 dims) → ~83%  (real runs: 81–83%)
    "failure_rates": {
        "incomplete_answer": 0.07,
        "safety_violations": 0.01,
        "unrealistic_tools": 0.02,
        "overcomplicated_solution": 0.03,
        "missing_context": 0.04,
        "poor_quality_tips": 0.06,
    },
    "quality_rates": {
        "answer_coherence": 0.99,
        "answer_completeness": 0.97,
        "appropriate_scope": 0.99,
        "category_accuracy": 0.99,
        "problem_answer_alignment": 0.98,
        "safety_specificity": 0.96,
        "step_actionability": 0.98,
        "tip_usefulness": 0.97,
        "tool_realism": 0.99,
    },
    "agreement_rate": 0.88,
}


# ---------------------------------------------------------------------------
# Step 4: Generate failure labels
# ---------------------------------------------------------------------------

def generate_failure_labels(
    valid_results: list[ValidatedResult],
    rng: numpy.random.Generator,
    failure_rates: dict[str, float] | None,
    output_dir: Path,
) -> pd.DataFrame:
    """Synthetic failure labels via per-dimension Bernoulli draws."""
    rates = failure_rates or MOCK_DEFAULTS["failure_rates"]
    n = len(valid_results)

    # Draw all dims at once: shape (n,) per dim
    draws: dict[str, list[int]] = {
        dim: rng.binomial(1, rates[dim], size=n).tolist()
        for dim in FAILURE_MODE_FIELDS
    }

    label_results: list[FailureLabelResult] = []
    for i, result in enumerate(valid_results):
        dim_vals = [draws[dim][i] for dim in FAILURE_MODE_FIELDS]
        label_results.append(FailureLabelResult(
            trace_id=result.trace_id,
            category=result.category,
            incomplete_answer=dim_vals[0],
            safety_violations=dim_vals[1],
            unrealistic_tools=dim_vals[2],
            overcomplicated_solution=dim_vals[3],
            missing_context=dim_vals[4],
            poor_quality_tips=dim_vals[5],
            overall_failure=int(any(v == 1 for v in dim_vals)),
            failure_count=sum(dim_vals),
        ))

    df = pd.DataFrame([r.model_dump() for r in label_results])
    df.to_csv(output_dir / "failure_labeled_data.csv", index=False)
    df.to_json(output_dir / "failure_labeled_data.json", orient="records", indent=2)
    print(f"Mock failure labeling: {df['overall_failure'].mean()*100:.1f}% overall failure rate")
    return df


# ---------------------------------------------------------------------------
# Step 5: Generate quality evals
# ---------------------------------------------------------------------------

def generate_quality_evals(
    valid_results: list[ValidatedResult],
    rng: numpy.random.Generator,
    quality_rates: dict[str, float] | None,
    output_dir: Path,
) -> pd.DataFrame:
    """Synthetic quality eval scores via per-dimension Bernoulli draws."""
    rates = quality_rates or MOCK_DEFAULTS["quality_rates"]
    n = len(valid_results)

    draws: dict[str, list[int]] = {
        dim: rng.binomial(1, rates[dim], size=n).tolist()
        for dim in QUALITY_DIMENSION_FIELDS
    }

    eval_results: list[QualityEvalResult] = []
    for i, result in enumerate(valid_results):
        dim_vals = [draws[dim][i] for dim in QUALITY_DIMENSION_FIELDS]
        eval_results.append(QualityEvalResult(
            trace_id=result.trace_id,
            category=result.category,
            answer_coherence=dim_vals[0],
            answer_completeness=dim_vals[1],
            appropriate_scope=dim_vals[2],
            category_accuracy=dim_vals[3],
            problem_answer_alignment=dim_vals[4],
            safety_specificity=dim_vals[5],
            step_actionability=dim_vals[6],
            tip_usefulness=dim_vals[7],
            tool_realism=dim_vals[8],
            overall_quality_pass=int(all(v == 1 for v in dim_vals)),
        ))

    df = pd.DataFrame([r.model_dump() for r in eval_results])
    df.to_csv(output_dir / "quality_eval_data.csv", index=False)
    df.to_json(output_dir / "quality_eval_data.json", orient="records", indent=2)
    print(f"Mock quality eval: {df['overall_quality_pass'].mean()*100:.1f}% overall quality pass rate")
    return df


# ---------------------------------------------------------------------------
# Step 6: Generate human labels
# ---------------------------------------------------------------------------

def generate_human_labels(
    valid_results: list[ValidatedResult],
    quality_df: pd.DataFrame,
    rng: numpy.random.Generator,
    agreement_rate: float | None,
    output_dir: Path,
) -> list[dict]:
    """Mock human labels by perturbing LLM quality eval scores with agreement noise."""
    flip_prob = 1.0 - (agreement_rate if agreement_rate is not None else MOCK_DEFAULTS["agreement_rate"])
    qdf_by_id = quality_df.set_index("trace_id").to_dict("index")

    human_dims = list(HUMAN_TO_LLM.keys())
    labels: list[dict] = []
    for result in valid_results:
        if result.trace_id not in qdf_by_id:
            continue
        qrow = qdf_by_id[result.trace_id]
        dim_vals: dict[str, int] = {}
        for human_key, llm_key in HUMAN_TO_LLM.items():
            llm_val = int(qrow[llm_key])
            flip = int(rng.binomial(1, flip_prob))
            dim_vals[human_key] = int(llm_val ^ flip)  # XOR binary flip

        labels.append({
            "trace_id": result.trace_id,
            "category": result.category,
            "labeler": "human",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            **dim_vals,
            "overall_pass": int(all(v == 1 for v in dim_vals.values())),
        })

    (output_dir / "human_labels.json").write_text(
        json.dumps(labels, indent=2, ensure_ascii=False)
    )
    agreement_approx = 1.0 - flip_prob
    print(f"Mock human labels: {len(labels)} records, ~{agreement_approx*100:.0f}% agreement rate")
    return labels


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def run_mock_pipeline(
    batch_label: str = "baseline-mock",
    num_samples: int = 50,
    seed: int = 42,
    skip_human_labels: bool = False,
    output_dir_base: Path | None = None,
    failure_rates: dict[str, float] | None = None,
    quality_rates: dict[str, float] | None = None,
    agreement_rate: float | None = None,
) -> Path:
    """Run the full mock pipeline end-to-end. Returns the batch output directory."""
    output_dir_base = output_dir_base or Path("output")
    output_dir = output_dir_base / batch_label

    if output_dir.exists() and any(output_dir.iterdir()):
        print(f"WARNING: batch dir already exists and contains files: {output_dir}")
        print("  Existing files will be overwritten. Use --batch-label to choose a different name.")

    output_dir.mkdir(parents=True, exist_ok=True)

    rng = numpy.random.default_rng(seed)

    # Steps 1+2 — Sample benchmark rows and wrap as GenerationResult
    from phase1_generation import run_generation_phase
    gen_results = run_generation_phase(
        num_samples=num_samples,
        generation_model="mock",
        output_dir=output_dir,
        batch_label=batch_label,
        seed=seed,
        output_base=output_dir_base,
    )

    # Step 3 — Run real Phase 2 (structural validation + heuristic gates)
    from phase2_validation import run_validation_phase
    valid_results, summary = run_validation_phase(gen_results, output_dir)

    if len(valid_results) == 0:
        raise RuntimeError(
            "All benchmark rows failed Phase 2 validation. "
            "The Benchmark dataset content may not satisfy the QAPair schema or heuristic gates."
        )
    if len(valid_results) < num_samples // 2:
        print(
            f"WARNING: only {len(valid_results)}/{num_samples} samples survived Phase 2. "
            f"Benchmark data may not satisfy all heuristic gates (e.g. safety_info < 80 chars)."
        )

    # Step 4 — Synthetic failure labels (no LLM call)
    failure_df = generate_failure_labels(valid_results, rng, failure_rates, output_dir)

    # Step 5 — Synthetic quality evals (no LLM call)
    quality_df = generate_quality_evals(valid_results, rng, quality_rates, output_dir)

    # Step 6 — Mock human labels
    if not skip_human_labels:
        generate_human_labels(valid_results, quality_df, rng, agreement_rate, output_dir)

    # Step 7 — Real Phase 6 analysis + charts
    from phase6_analysis import run_analysis_phase
    run_analysis_phase(output_dir=output_dir)

    return output_dir
